language: java
before_install:
  - sudo apt-get install ant
  - sudo apt-get install ant-optional
  - sudo apt install openjdk-8-jdk openjfx
  - export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/"
  - sudo apt-get install junit4
  - whereis ant
  - export ANT_HOME="/usr/share/ant/"
  - export CLASSPATH="/usr/share/java/junit4.jar"
jdk:
  - openjdk8

install: ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - amaruduran@gmail.com
      - violetaperezandrade@hotmail.com
      - romerogerard@hotmail.com
      - gabigbell@hotmail.com
    on_failure: always
    on_success: never
