language: java
before_install:
  - sudo apt-get install ant
  - export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/"
  - sudo apt-get install junit4
  - export CLASSPATH="/usr/share/java/junit4.jar"
  - whereis ant
jdk:
  - openjdk8

install: ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - amaruduran@gmail.com
    on_failure: always
